### PR TITLE
Fix broken links in Features and Actions

### PR DESCRIPTION
**Pull request by freak4pc**
Noticed a few broken links on one of the docs pages :)

### CODE REVIEW

**Comment by marcpalmer** [comment]
Hi @freak4pc  - thanks for this.

However are you seeing these problems on http://flint.tools/manual/guides/features_and_actions.html ?

If not, there is no problem. We pull the docs from the repo down into Jekyll to build the site. Use flint.tools as your doc reference. I should remove links to the docs repo from other places - that is probably the right fix.

Let me know!

**Comment by freak4pc** [comment]
Looks fine in the site itself, but many people read documentation inline in GitHub, so I would personally suggest finding a way to make both link options work :) Not sure if its a possibility, but its different worth the research. (Even if it means possibly just dropping `.md` from links in Jekyll) 

Thanks for the comment.

**Comment by marcpalmer** [comment]
No worries. I thought it was working in both, I'll check up on it.

Github will not be a good option for viewing the docs. We need YAML to make the jekyll site work well, and there are other issues with macros and images that don't work in the github environment.. 

Obviously I'd like it to, but it is more important we have high quality and easily accessible docs on the main website. We'll see if we can improve things.

**Comment by marcpalmer** [comment]
Confirm that the inter-doc links do not work generally when viewed on github. I'm not sure there's much I can do because of the way Jekyll resolves the links but I'll try. If .md works everwhere we're golden. Thanks again for taking the time, it is much appreciated!

**Comment by freak4pc** [comment]
Sure thing!

**Comment by marcpalmer** [comment]
Opened issue #4 to track this

**Pull request closed without merging**
